# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#


development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: db/alpha_development
  pool: 5
  username: root
  password: oracle
  socket: /tmp/mysql.sock


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: db/alpha_production
  pool: 5
  username: root
  password: oracle
  socket: /tmp/mysql.sock