:output:
  User:
    :options:
      :fields:
        - id
        - email
        - role
        - actif


  Roster:
    :options:
      :fields:
        - id
        - mission_id
        - user_id
        - convoc
        - but
        - butvilledepart
        - comment
        - harrivee
        - hdepart

  Jour:
      :options:
        :fields:
          - id
          - roster_id
          - convocationjour_id

  Mission:
      :options:
        :fields:
          - id
          - name
          - encours

  Convocationjour:
      :options:
        :fields:
          - id
          - mission_id
          - jourconvoc
