:output:
  User:
    :options:
      :fields:
        - id
        - email
        - role


  Roster:
    :options:
      :fields:
        - id
        - codeactivite
        - user_id
        - convoc
        - but
        - butvilledepart
        - comment
        - harrivee
        - hdepart

  Jour:
      :options:
        :fields:
          - id
          - roster_id
          - jourpresent