:output:
  User:
    :options:
      :fields:
        - id
        - email
        - role

  Roster:
    :options:
      :fields:
        - id
        - codeactivite
        - user_id
        - datedebut
        - datefin